" .vimrc, init.vim
if !1 | finish | endif
if v:version < 800
  finish
endif

" settings
let g:base_path = expand('$HOME/.vim')
let g:after_path = g:base_path . '/after'
let g:use_packmgr_minpac = 0
let g:use_packmgr_vim_plug = 1

" set path
set runtimepath&
if match(&runtimepath, g:base_path) == -1
  execute 'set runtimepath ^=' . g:base_path
endif
if match(&runtimepath, g:after_path) == -1
  execute 'set runtimepath +=' . g:after_path
endif
set packpath&

" load parameters
runtime! init/settings/*.vim

" load util
runtime! init/util/*.vim

" load packages from package manager
runtime! init/packconf/*.vim
runtime! init/packmgr/*.vim

" load other settings
runtime! init/*.vim

" EOF
