" .vimrc, init.vim
if !1
  finish
endif

" settings
let g:base_path = expand('$HOME/.vim')
let g:after_path = g:base_path . '/after'

" basic settings
if has('vim_starting')
  set encoding=utf-8
endif
execute 'source ' . g:base_path . '/init/keybindings_basic.vim'

" vim8
if v:version < 800
  finish
endif

" set path
set runtimepath&
set packpath&
if match(&runtimepath, g:base_path) == -1
  execute 'set runtimepath ^=' . g:base_path
endif
if match(&runtimepath, g:after_path) == -1
  execute 'set runtimepath +=' . g:after_path
endif

" load init settings
execute 'source ' . g:base_path . '/init/settings.vim'
execute 'source ' . g:base_path . '/init/tools.vim'

" set basic settings
filetype plugin indent on
if ! exists("g:syntax_on")
  syntax enable
endif
if has('termguicolors')
  set termguicolors
endif
if Params('term') !~ '^xterm' && ! has('gui_running')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" load package settingss
execute 'source ' . g:base_path . '/init/packset/vim-easymotion.vim'
execute 'source ' . g:base_path . '/init/packset/vim-surround.vim'
" load package manager
execute 'source ' . g:base_path . '/init/packmgr/minpac.vim'
execute 'source ' . g:base_path . '/init/packmgr/vim-plug.vim'
" load other settings
execute 'source ' . g:base_path . '/init/keybindings.vim'
execute 'source ' . g:base_path . '/init/other.vim'
execute 'source ' . g:base_path . '/init/lines.vim'
execute 'source ' . g:base_path . '/init/gui.vim'

" EOF
