set guifont=HackGenNerd\ Console\ 12,Myrica\ M\ 13.5
set guifontwide=HackGenNerd\ Console\ 12,Myrica\ M\ 13.5
set guioptions+=a
set guioptions-=e
set guioptions-=m
set guioptions-=T
set guioptions-=l
set guioptions-=r
set guioptions-=L
set guioptions-=R
set guioptions-=b
