if !1
    finish
endif

" directory path
let g:dotvim_dir = expand("<sfile>:p:h")

" basic settings
if has('vim_starting')
    set encoding=utf-8
endif

" load basic
execute "source " . g:dotvim_dir . "/config.vim"
execute "source " . g:dotvim_dir . "/utils.vim"
execute 'source ' . g:dotvim_dir . '/keybindings/keybindings.vim'

if v:version < g:CONFIG["min_required"]
    finish
endif

" set path
set runtimepath&
set packpath&
if match(&runtimepath, g:dotvim_dir) == -1
    execute 'set runtimepath ^=' . g:dotvim_dir
endif
if match(&runtimepath, g:CONFIG["after_dir"]) == -1
    execute 'set runtimepath +=' . g:CONFIG["after_dir"]
endif

" set basic settings
filetype plugin indent on
if ! exists("g:syntax_on")
    syntax enable
endif
if has('termguicolors')
    set termguicolors
endif
if g:CONFIG['term'] !~ '^xterm' && ! has('gui_running')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

execute 'source ' . g:dotvim_dir . '/package_manager.vim'
execute 'source ' . g:dotvim_dir . '/misc.vim'
execute 'source ' . g:dotvim_dir . '/tab_line.vim'
execute 'source ' . g:dotvim_dir . '/status_line.vim'

if has('gui_running')
    execute 'source ' . g:dotvim_dir . '/gui.vim'
endif
