if !1
    finish
endif
noremap j gj
noremap k gk
noremap! <C-f> <right>
noremap! <C-b> <left>
inoremap <C-a> <C-o>0
inoremap <C-e> <C-o>$
cnoremap <C-a> <C-b>
cnoremap <C-e> <C-e>
noremap! <C-h> <bs>
noremap! <C-d> <del>
inoremap <C-y> <C-o>p
cnoremap <C-y> <C-r>"
noremap! <C-q> <C-v>
nnoremap K <Nop>
nnoremap ZQ <Nop>
nnoremap ZZ <Nop>

if v:version < 800
    finish
endif

" directory path
let g:dotvim_dir = expand("<sfile>:p:h")

" basic settings
if has('vim_starting')
    set encoding=utf-8
endif

" load basic
execute "source " . g:dotvim_dir . "/config.vim"
execute "source " . g:dotvim_dir . "/utils.vim"

" set path
set runtimepath&
set packpath&
if match(&runtimepath, g:dotvim_dir) == -1
    execute 'set runtimepath ^=' . g:dotvim_dir
endif
if match(&runtimepath, g:CONFIG["after_dir"]) == -1
    execute 'set runtimepath +=' . g:CONFIG["after_dir"]
endif

" set basic settings
filetype plugin indent on
if ! exists("g:syntax_on")
    syntax enable
endif
if has('termguicolors')
    set termguicolors
endif
if g:CONFIG['term'] !~ '^xterm' && ! has('gui_running')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

execute 'source ' . g:dotvim_dir . '/packages/configs_before.vim'
execute 'source ' . g:dotvim_dir . '/packages/manager.vim'
execute 'source ' . g:dotvim_dir . '/packages/configs_after.vim'
execute 'source ' . g:dotvim_dir . '/keybindings/main.vim'
execute 'source ' . g:dotvim_dir . '/tab_line.vim'
execute 'source ' . g:dotvim_dir . '/status_line.vim'
execute 'source ' . g:dotvim_dir . '/misc.vim'

if has('gui_running')
    execute 'source ' . g:dotvim_dir . '/gui.vim'
endif
